# /shared/Cargo.toml

[package]
name = "shared"
version = "0.1.0"
authors = ["LeonGGX <email@address.com>"]
edition = "2018"

[dependencies]
serde = { version = "^1.0.106", features = ['derive'] }
serde_json = "1.0.45"
bson = "0.14.1"
